## Feed Forward Backpropagation Neural Network

In [2]:
# Importing the modules
import numpy as np

In [2]:
class NeuralNetwork():
    
    def __init__(self):
        np.random.seed()
        self.synaptic_weights = 2*np.random.random((3,1))-1
        
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    
    def sigmoid_derivative(self,x):
        return x*(1-x)
    
    def train(self, train_in, train_out, training_iter):
        for iter in range(training_iter):
            output = self.think(train_in)
            error = train_out - output
            adjust = np.dot(train_in.T,error*self.sigmoid_derivative(output))
            self.synaptic_weights += adjust
    
    def think(self, inputs):
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs,self.synaptic_weights))
        return output
    
if __name__=='__main__':
    
    neural_network = NeuralNetwork()
    
    print("Beginning randomly generated weights: ")
    print(neural_network.synaptic_weights,"\n")
    
    train_in = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
    train_out = np.array([[0,1,1,0]]).T
    
    neural_network.train(train_in, train_out, 15000)
    
    print("Ending weights after training: ")
    print(neural_network.synaptic_weights,"\n")
    print("Outputs after training: ")
    print(neural_network.think(train_in))

Beginning randomly generated weights: 
[[ 0.13465992]
 [-0.93153358]
 [ 0.71042747]] 

Ending weights after training: 
[[10.08731134]
 [-0.20781323]
 [-4.83701678]] 

Outputs after training: 
[[0.00786828]
 [0.99358373]
 [0.9947814 ]
 [0.00640131]]


In [3]:
user_input_one = str(input("User Input One:"))
user_input_Two = str(input("User Input Two:"))
user_input_Three = str(input("User Input Three:"))

print("Considering new situation:",user_input_one, user_input_Two, user_input_Three)
print("New output data: ")
print(neural_network.think(np.array([user_input_one, user_input_Two, user_input_Three])))

User Input One:1
User Input Two:0
User Input Three:1
Considering new situation: 1 0 1
New output data: 
[0.9947814]


In [3]:
x = 2*np.random.random((3,1))-1
print(x)

[[0.32013108]
 [0.21447689]
 [0.66587592]]


In [12]:
np.random.seed(42)
2*np.random.random((3,1))-1

array([[-0.25091976],
       [ 0.90142861],
       [ 0.46398788]])

In [8]:
2*0.95071431

1.90142862

In [9]:
2*0.37454012

0.74908024

In [10]:
2*0.66587592

1.33175184

In [13]:
1.90142862-1

0.9014286199999999

In [14]:
2*0.37454012-1

-0.25091976000000005